### ISSUE TITLE
インデントの不揃い

### ISSUE THREAD

**Issue by hidaytours** [tkc-poly-tech/refactor_tetris#2]
インデントを揃える必要あり
チーム内でフォーマッタの設定を共有しフォーマッタを適用する

**Comment by hidaytours** [comment]
二人ともvscodeで作業しているのでvscodeのフォーマッタ設定を調べる
参考になりそうなURLを貼っていく

**Comment by tkc-poly-tech** [comment]
・[【VSCode】ワークスペース設定を共有](https://kakkoyakakko2.hatenablog.com/entry/2018/10/14/003000)

**Comment by hidaytours** [comment]
現在の自分のvscodeの設定を記載
- インデントのサイズ指定：editor.tabSize
  - 4
- Tabキーを押した場合に空白指定：editor.insertSpaces
  - 無効
- ファイルエンコーディングの指定：files.encoding
  - UTF-8 
- 改行コード：files.eol
  - auto(\n)
- 保存時にファイルの末尾に空の新規行を追加：files.insertFinalNewline
  - 無効
- 行の末尾の空白を除去：files.trimTrailingWhitespace
  - 無効
- 制御文字の表示：editor.renderControlCharacters
  - 有効
- 拡張機能の標準設定
  - C/C++
    - コーディングスタイル：C_Cpp.clang_format_style 
      - file
    - 書式設定エンジン：C_Cpp.formatting
      - Default (clang-format)

**Comment by tkc-poly-tech** [comment]
- インデントのサイズ指定：editor.tabSize: 4
- Tabキーを押した場合に空白指定：editor.insertSpaces: false
- ファイルエンコーディングの指定：files.encoding: utf8
- 改行コード：files.eol: auto
- 保存時にファイルの末尾に空の新規行を追加：files.insertFinalNewline: false
- 行の末尾の空白を除去：files.trimTrailingWhitespace: false
- 制御文字の表示：editor.renderControlCharacters: true
- 拡張機能の標準設定C/C++：
   - C_Cpp.clang_format_style: file
   - C_Cpp.formatting: Default

私の方も確認してみて同じでした。

**Comment by hidaytours** [comment]
close
