### ISSUE TITLE
ソースファイルの分割

### ISSUE THREAD

**Issue by hidaytours** [tkc-poly-tech/refactor_tetris#4]
一つにまとまっているコードを分割する

**Comment by hidaytours** [comment]
点数管理とタイマー管理をscore.cとtimer.cに分割

**Comment by tkc-poly-tech** [comment]
Piece系の一部(copyPiece, deletePiece, rotatePiece)を分割

**Comment by tkc-poly-tech** [comment]
Table系を使うコードを分割する

**Comment by hidaytours** [comment]
current系、getch系に関して関数化及び分割できないか検討

**Comment by tkc-poly-tech** [comment]
main.cのみ分割するかの検討
