### ISSUE TITLE
適切なコメント

### ISSUE THREAD

**Issue by tkc-poly-tech** [tkc-poly-tech/refactor_tetris#6]
参考にしたコードのコメントの通り私が書いてしまっていて、出来ればコメントを考え直したい。

**Comment by tkc-poly-tech** [comment]
ピース概形をわかりやすくする為、コメントでピースの概略を書く必要があるか検討

**Comment by hidaytours** [comment]
- rotatePieceのコメントを"90 degrees clockwise rotate"に変更
- validation.cのコメント削除

**Comment by tkc-poly-tech** [comment]
#29
